settings:
  name: "NetApp Database solutions"
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    lipi_enabled: true
  pdf: 
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-databases.zip

product-family:
  name: NetApp Solutions
  repo: netapp-solutions-family

sidebar:
  entries:
    - title: "Database solutions"
      url: /index.html
    - section: databases
    
    - title: "Video Collection"
      url: /videos.html
    - title: "Blogs"
      url: /blogs.html
    - title: "Change Log"
      url: /whats-new.html
    - title: "Learn about NetApp Solutions"
      url: https://docs.netapp.com/us-en/netapp-solutions-family/intro-family.html
    - title: "Legal notices"
      url: /legal-notices.html
